# Generated by Django 3.2 on 2023-10-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_recomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomment',
            old_name='recomment',
            new_name='movie',
        ),
    ]
